# 배열간 비교 연산

In [2]:
import numpy as np
from numpy.random import choice

In [5]:
matrix_1 =  choice(range(100),9).reshape(3,3)
matrix_2 =  choice(range(100),9).reshape(3,3)

In [6]:
matrix_1, matrix_2

(array([[87, 41, 60],
        [51, 38, 93],
        [78, 13, 10]]),
 array([[21, 96, 54],
        [14, 83, 87],
        [12, 26,  9]]))

In [8]:
print(matrix_1 > matrix_2)
print(matrix_1 >= matrix_2)
print(matrix_1 == matrix_2)
print(matrix_1 != matrix_2)
print(matrix_1 < matrix_2)
print(matrix_1 <= matrix_2)

[[ True False  True]
 [ True False  True]
 [ True False  True]]
[[ True False  True]
 [ True False  True]
 [ True False  True]]
[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False  True False]
 [False  True False]
 [False  True False]]
[[False  True False]
 [False  True False]
 [False  True False]]


In [9]:
# true false를 배열의 인덱스로 사용해서 true에 해당하는 데이터만 추출

In [13]:
print(matrix_1[matrix_1 > matrix_2])
print(matrix_1[matrix_1 >= matrix_2])
print(matrix_1[matrix_1 == matrix_2])
print(matrix_1[matrix_1 != matrix_2])
print(matrix_1[matrix_1 < matrix_2])
print(matrix_1[matrix_1 <= matrix_2])

[87 60 51 93 78 10]
[87 60 51 93 78 10]
[]
[87 41 60 51 38 93 78 13 10]
[41 38 13]
[41 38 13]


In [11]:
matrix_1[ matrix_1 > matrix_2  ]

array([87, 60, 51, 93, 78, 10])

In [26]:
student_score =  choice(range(60,100),9)
student_score

array([95, 85, 78, 78, 66, 68, 83, 80, 83])

In [27]:
student_names = np.array(['a','b','c','d','e','f','g','h','i'])
student_names

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [28]:
# 점수가 70이상인 학생들을 출력
student_score>70

array([ True,  True,  True,  True, False, False,  True,  True,  True])

In [29]:
print(student_names[student_score>70])

['a' 'b' 'c' 'd' 'g' 'h' 'i']


# 판다스 Pandas
    데이터분석에 자주 사용되는 프레임웍

## 시리즈

In [33]:
!pip  install pandas

     --------------------------------------- 10.4/10.4 MB 59.5 MB/s eta 0:00:00


In [34]:
import pandas as pd

In [39]:
series_list_1 =  pd.Series([1,2,3,4,5])
print(series_list_1)
print()
print(series_list_1.index)
print()
print(series_list_1.values)

0    1
1    2
2    3
3    4
4    5
dtype: int64

RangeIndex(start=0, stop=5, step=1)

[1 2 3 4 5]


In [40]:
series_list_1 =  pd.Series([1,2,3,4,5], index = [10,20,30,40,50])
print(series_list_1)
print()
print(series_list_1.index)
print()
print(series_list_1.values)

10    1
20    2
30    3
40    4
50    5
dtype: int64

Int64Index([10, 20, 30, 40, 50], dtype='int64')

[1 2 3 4 5]


In [41]:
series_list_1 =  pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
print(series_list_1)
print()
print(series_list_1.index)
print()
print(series_list_1.values)

a    1
b    2
c    3
d    4
e    5
dtype: int64

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

[1 2 3 4 5]


In [52]:
series_list_1 =  pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
print(series_list_1)
print()
print(series_list_1.index)
print()
print(series_list_1.values)

a    1
b    2
c    3
d    4
e    5
dtype: int64

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

[1 2 3 4 5]


### 딕셔너리로 시리즈 생성하기

In [55]:
dic_data = {'치킨' : 32000, '피자' : 25000, '햄버거' : 7000 }
series_list_a = pd.Series(dic_data)
series_list_a

치킨     32000
피자     25000
햄버거     7000
dtype: int64

In [63]:
delivery_food = ['치킨','피자','햄버거','짜장면']
dic_data = {'치킨' : 32000, '피자' : 25000, '햄버거' : 7000 }

series_list_a = pd.Series(dic_data, index = delivery_food)
series_list_a

치킨     32000.0
피자     25000.0
햄버거     7000.0
짜장면        NaN
dtype: float64

In [62]:
series_list_b = pd.Series([1,2,3,4], index = delivery_food)
series_list_b

치킨     1
피자     2
탕수육    3
짜장면    4
dtype: int64

### NaN : Not a Number --> 결측치

In [64]:
# 시리즈에서 값을 찾을때
print(series_list_a['치킨'])
# 여러개를 찾을때
print(series_list_a[ ['치킨','피자'] ])

32000.0
치킨    32000.0
피자    25000.0
dtype: float64


In [65]:
# 조건에 해당하는 값을 찾을때
series_list_a > 20000

치킨      True
피자      True
햄버거    False
짜장면    False
dtype: bool

In [66]:
series_list_a[ series_list_a > 20000 ]

치킨    32000.0
피자    25000.0
dtype: float64

In [67]:
# 인덱스가 있는지 확인할때
print('치킨' in series_list_a)

True
