# 중복데이터 처리

In [1]:
import pandas as pd

In [4]:
df = pd.DataFrame(
    {
        'c1':['a','a','b','a','b'],
        'c2':[1,1,2,2,2],
        'c3' : [1,1,2,2,2]
    }
)
df

c1  c2  c3
0  a   1   1
1  a   1   1
2  b   2   2
3  a   2   2
4  b   2   2

In [5]:
df.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [7]:
df['c2'].duplicated()

0    False
1     True
2    False
3     True
4     True
Name: c2, dtype: bool

In [8]:
df.drop_duplicates()

c1  c2  c3
0  a   1   1
2  b   2   2
3  a   2   2

In [10]:
df.drop_duplicates(subset=['c1','c2'])

c1  c2  c3
0  a   1   1
2  b   2   2
3  a   2   2

# 데이터 표준화

In [12]:
df = pd.read_csv('https://raw.githubusercontent.com/leekyuyoung20221226/python/main/data/auto-mpg.csv', header=None)

In [14]:
df.columns = ['mpeg','cylinders','displacement','hoursepower','weight','acceleration','model year','origin','name']

In [15]:
df.head()

mpeg  cylinders  displacement hoursepower  weight  acceleration  \
0  18.0          8         307.0       130.0  3504.0          12.0   
1  15.0          8         350.0       165.0  3693.0          11.5   
2  18.0          8         318.0       150.0  3436.0          11.0   
3  16.0          8         304.0       150.0  3433.0          12.0   
4  17.0          8         302.0       140.0  3449.0          10.5   

   model year  origin                       name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1              amc rebel sst  
4          70       1                ford torino

# 단위 환산

In [18]:
# mpg ,kpi 로 변환  
# 1마일 : 1.6093km  1갤런 : 3.78541리터
mpg_to_kpl = 1.6093 / 3.78541
df['kpl'] = (df['mpeg'] * mpg_to_kpl).round(2)

In [19]:
df.head()

mpeg  cylinders  displacement hoursepower  weight  acceleration  \
0  18.0          8         307.0       130.0  3504.0          12.0   
1  15.0          8         350.0       165.0  3693.0          11.5   
2  18.0          8         318.0       150.0  3436.0          11.0   
3  16.0          8         304.0       150.0  3433.0          12.0   
4  17.0          8         302.0       140.0  3449.0          10.5   

   model year  origin                       name   kpl  
0          70       1  chevrolet chevelle malibu  7.65  
1          70       1          buick skylark 320  6.38  
2          70       1         plymouth satellite  7.65  
3          70       1              amc rebel sst  6.80  
4          70       1                ford torino  7.23

# 자료형 변환
    숫자가 문자열(object)로 저장된 경우 숫자형으로 변환
    각 열의 자료형을 확인 - info() dttypes

In [20]:
df.dtypes

mpeg            float64
cylinders         int64
displacement    float64
hoursepower      object
weight          float64
acceleration    float64
model year        int64
origin            int64
name             object
kpl             float64
dtype: object

In [21]:
# model year, origin은 범주형 데이터
# hoursepower 는 수치형
# tip ; csv 로 가져올때 원래 수치형 데이터였는데.. 컬럼중에 문자열이 하나라도 포함되어 있으면 object로 변환되서 가져온다.
# 확인방법

In [22]:
df['hoursepower'].unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '?', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [24]:
import numpy as np
df['hoursepower'].replace('?', np.nan,inplace=True)

In [27]:
df[df['hoursepower'].isnull()]

mpeg  cylinders  displacement hoursepower  weight  acceleration  \
32   25.0          4          98.0         NaN  2046.0          19.0   
126  21.0          6         200.0         NaN  2875.0          17.0   
330  40.9          4          85.0         NaN  1835.0          17.3   
336  23.6          4         140.0         NaN  2905.0          14.3   
354  34.5          4         100.0         NaN  2320.0          15.8   
374  23.0          4         151.0         NaN  3035.0          20.5   

     model year  origin                  name    kpl  
32           71       1            ford pinto  10.63  
126          74       1         ford maverick   8.93  
330          80       2  renault lecar deluxe  17.39  
336          80       1    ford mustang cobra  10.03  
354          81       2           renault 18i  14.67  
374          82       1        amc concord dl   9.78

In [28]:
df.dropna(subset=['hoursepower'],axis=0,inplace=True)

In [30]:
df.hoursepower =  df.hoursepower.astype('float')

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpeg          392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   hoursepower   392 non-null    float64
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64  
 7   origin        392 non-null    int64  
 8   name          392 non-null    object 
 9   kpl           392 non-null    float64
dtypes: float64(6), int64(3), object(1)
memory usage: 33.7+ KB


In [32]:
df.origin.unique()  # 1 : USA  2: EU  3:JPN

array([1, 3, 2], dtype=int64)

In [33]:
df['origin_obj'] = df['origin'].replace( {1:'USA',2:'EU',3:'JPN'} )

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpeg          392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   hoursepower   392 non-null    float64
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64  
 7   origin        392 non-null    int64  
 8   name          392 non-null    object 
 9   kpl           392 non-null    float64
 10  origin_obj    392 non-null    object 
dtypes: float64(6), int64(3), object(2)
memory usage: 36.8+ KB


In [38]:
df['origin_obj'] = df['origin_obj'].astype('str')

In [43]:
df['model year'].sample(3)

50     71
147    74
268    78
Name: model year, dtype: int64

In [44]:
df['model year'] = df['model year'].astype('category')
df['model year'].sample(3)

45     71
206    76
177    75
Name: model year, dtype: category
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]

# 범주형(카테고리)데이터 처리
    성적에따른 학점 부여
    구간을 정하기 애매할때..    

In [47]:
count, bin_dividers =  np.histogram( df.hoursepower, bins=3)

In [48]:
count, bin_dividers

(array([257, 103,  32], dtype=int64),
 array([ 46.        , 107.33333333, 168.66666667, 230.        ]))

In [49]:
bin_names = ['저출력','보통출력','고출력']
df['hp_bin'] = pd.cut(x=df['hoursepower'],
                      bins =bin_dividers,
                      labels=bin_names,
                      include_lowest=True  # 첫 경계값 포함
                     )

In [52]:
df.hp_bin.unique()

['보통출력', '고출력', '저출력']
Categories (3, object): ['저출력' < '보통출력' < '고출력']

In [53]:
df[['hoursepower','hp_bin']]

hoursepower hp_bin
0          130.0   보통출력
1          165.0   보통출력
2          150.0   보통출력
3          150.0   보통출력
4          140.0   보통출력
..           ...    ...
393         86.0    저출력
394         52.0    저출력
395         84.0    저출력
396         79.0    저출력
397         82.0    저출력

[392 rows x 2 columns]

In [54]:
df.head(1)

mpeg  cylinders  displacement  hoursepower  weight  acceleration  \
0  18.0          8         307.0        130.0  3504.0          12.0   

  model year  origin                       name   kpl origin_obj hp_bin  
0         70       1  chevrolet chevelle malibu  7.65        USA   보통출력

# 더미변수 - oneHot
    hp_bin 같은 경우는 바로 머신러닝에서 사용 불가 why : 계산불가. 수치가 아니기 때문에
    데이터의 속성은 제거하면서 어떤 특성(Feature)이 있는지 없는지 여부만 표시
    0과 1로 표현
    010
    100
    001

In [59]:
horsepower_dummes =  pd.get_dummies(df['hp_bin'])
horsepower_dummes.head(20)

저출력  보통출력  고출력
0     0     1    0
1     0     1    0
2     0     1    0
3     0     1    0
4     0     1    0
5     0     0    1
6     0     0    1
7     0     0    1
8     0     0    1
9     0     0    1
10    0     0    1
11    0     1    0
12    0     1    0
13    0     0    1
14    1     0    0
15    1     0    0
16    1     0    0
17    1     0    0
18    1     0    0
19    1     0    0

In [62]:
!pip install scikit-learn

     ---------------------------------------- 8.2/8.2 MB 27.7 MB/s eta 0:00:00
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
     ------------------------------------- 298.0/298.0 kB 18.0 MB/s eta 0:00:00
     --------------------------------------- 42.5/42.5 MB 29.7 MB/s eta 0:00:00


In [63]:
from sklearn import preprocessing

In [64]:
label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

In [78]:
onehot_labeled =  label_encoder.fit_transform(df['hp_bin'])
onehot_labeled[:5] # 너무 많아서 5개만

array([1, 1, 1, 1, 1])

In [77]:
# 2차원 행렬 형태로 변환
onthot_reshaped =  onehot_labeled.reshape(-1,1)
onthot_reshaped[:5]  # 너무 많아서 5개만

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [80]:
len(onthot_reshaped)

392

In [82]:
#희소행렬
onehot_fitted =  onehot_encoder.fit_transform(onthot_reshaped)
print(onehot_fitted)
print(type(onehot_fitted))

  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 2)	1.0
  (15, 2)	1.0
  (16, 2)	1.0
  (17, 2)	1.0
  (18, 2)	1.0
  (19, 2)	1.0
  (20, 2)	1.0
  (21, 2)	1.0
  (22, 2)	1.0
  (23, 1)	1.0
  (24, 2)	1.0
  :	:
  (367, 2)	1.0
  (368, 2)	1.0
  (369, 2)	1.0
  (370, 2)	1.0
  (371, 2)	1.0
  (372, 2)	1.0
  (373, 2)	1.0
  (374, 2)	1.0
  (375, 2)	1.0
  (376, 2)	1.0
  (377, 2)	1.0
  (378, 2)	1.0
  (379, 2)	1.0
  (380, 1)	1.0
  (381, 2)	1.0
  (382, 2)	1.0
  (383, 1)	1.0
  (384, 2)	1.0
  (385, 2)	1.0
  (386, 2)	1.0
  (387, 2)	1.0
  (388, 2)	1.0
  (389, 2)	1.0
  (390, 2)	1.0
  (391, 2)	1.0
<class 'scipy.sparse._csr.csr_matrix'>


# 정규화
    A : 100,101,102,103,104
    B : 0.1,0.2,0.3,0.4,0.5
    데이터의 상대적인 차이를 제거... 정규화(normalization) : 0~1 or -1 ~ 1
    1. 각 데이터를 최대값으로 나눈다.  ( 0 ~ 255) / 255   (0 ~ 1)

In [84]:
df.describe()

mpeg   cylinders  displacement  hoursepower       weight  \
count  392.000000  392.000000    392.000000   392.000000   392.000000   
mean    23.445918    5.471939    194.411990   104.469388  2977.584184   
std      7.805007    1.705783    104.644004    38.491160   849.402560   
min      9.000000    3.000000     68.000000    46.000000  1613.000000   
25%     17.000000    4.000000    105.000000    75.000000  2225.250000   
50%     22.750000    4.000000    151.000000    93.500000  2803.500000   
75%     29.000000    8.000000    275.750000   126.000000  3614.750000   
max     46.600000    8.000000    455.000000   230.000000  5140.000000   

       acceleration      origin         kpl  
count    392.000000  392.000000  392.000000  
mean      15.541327    1.576531    9.967270  
std        2.758864    0.805518    3.317743  
min        8.000000    1.000000    3.830000  
25%       13.775000    1.000000    7.230000  
50%       15.500000    1.000000    9.675000  
75%       17.025000    2.000000   12.330000  
max       24.800000    3.000000   19.810000

In [87]:
df.hoursepower = df.hoursepower / df.hoursepower.max()

In [89]:
df.hoursepower.describe()

count    392.000000
mean       0.454215
std        0.167353
min        0.200000
25%        0.326087
50%        0.406522
75%        0.547826
max        1.000000
Name: hoursepower, dtype: float64

In [91]:
# 최대값 - 최소값 의 값으로 각 데이터를 나눈다.
# 각열의 값 - 최소값 / 최대값-최소값
# (x - min) / (max - min)  
# 최대값은 1이 된다

In [95]:
weight_min = df.weight.min()
weight_max = df.weight.max()
weight_minmax = weight_max - weight_min

In [100]:
df.weight = (df.weight - weight_min) / weight_minmax

In [101]:
df.weight.describe()

count    392.000000
mean       0.386897
std        0.240829
min        0.000000
25%        0.173589
50%        0.337539
75%        0.567550
max        1.000000
Name: weight, dtype: float64

In [102]:
# 전체데이터에 대해서 일괄적용 (두가지 방법중에 한개 선택)  0 ~ 1

# 시계열 데이터
    판다스는 시계열 데이터를 다루는 유용한 기능있다.
    시계열 데이터 ? 시간의 개념을 가진 연속적인 데이터로 순서가 있으며 순서가 바뀌면 의미도 바뀐다.
    판다스에서 시계열 데이터 표시하는 유형중에 두가지가 있는데
    Timestamp : 특정한  시점을 기록
    Period 두 지점사이의 일정한 기간

In [104]:
df =  pd.read_csv('https://raw.githubusercontent.com/leekyuyoung20221226/python/main/data/stock-data.csv')
df.head()

Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Date    20 non-null     object
 1   Close   20 non-null     int64 
 2   Start   20 non-null     int64 
 3   High    20 non-null     int64 
 4   Low     20 non-null     int64 
 5   Volume  20 non-null     int64 
dtypes: int64(5), object(1)
memory usage: 1.1+ KB


In [111]:
df['new_Data'] =  df.Date.astype(np.datetime64)
# pd.to_datetime(df.Date)

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      20 non-null     object        
 1   Close     20 non-null     int64         
 2   Start     20 non-null     int64         
 3   High      20 non-null     int64         
 4   Low       20 non-null     int64         
 5   Volume    20 non-null     int64         
 6   new_Data  20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 1.2+ KB


In [116]:
# datetime열을 인덱스열로 변경하고 date 열을 삭제
df.set_index('new_Data',inplace=True)

In [117]:
df.drop('Date',axis = 1,inplace=True)

In [118]:
df

Close  Start   High    Low  Volume
new_Data                                      
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039
2018-06-25  11150  11400  11450  11000   55519
2018-06-22  11300  11250  11450  10750  134805
2018-06-21  11200  11350  11750  11200  133002
2018-06-20  11550  11200  11600  10900  308596
2018-06-19  11300  11850  11950  11300  180656
2018-06-18  12000  13400  13400  12000  309787
2018-06-15  13400  13600  13600  12900  201376
2018-06-14  13450  13200  13700  13150  347451
2018-06-12  13200  12200  13300  12050  558148
2018-06-11  11950  12000  12250  11950   62293
2018-06-08  11950  11950  12200  11800   59258
2018-06-07  11950  12200  12300  11900   49088
2018-06-05  12150  11800  12250  11800   42485
2018-06-04  11900  11900  12200  11700   25171
2018-06-01  11900  11800  12100  11750   32062

In [119]:
# Period 로 변환  pd.to_period()

In [121]:
dates = ['2019-01-01','2020-03-01','2021-06-01']
ts_dates =  pd.to_datetime(dates)
ts_dates

DatetimeIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='datetime64[ns]', freq=None)

In [122]:
ts_dates.to_period(freq = 'D')

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='period[D]')

In [123]:
ts_dates.to_period(freq = 'M')

PeriodIndex(['2019-01', '2020-03', '2021-06'], dtype='period[M]')

In [126]:
ts_dates.to_period(freq = 'A')

PeriodIndex(['2019', '2020', '2021'], dtype='period[A-DEC]')

In [130]:
df.index.to_period(freq='A')

PeriodIndex(['2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018',
             '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018',
             '2018', '2018', '2018', '2018'],
            dtype='period[A-DEC]', name='new_Data')

# 시계열 데이터 만들기

##### Timestamp 배열

In [136]:
ts_ms = pd.date_range(start='2023-01-01',  # 시작날자
                      end=None,            # 날자 범위 끝
                      periods=6,           # 생성할 TimeStamp 수
                      freq='MS',            # 시간 간격(MS 월의 시작)
                      tz = 'Asia/Seoul'    # 시간대
                     )
ts_ms

DatetimeIndex(['2023-01-01 00:00:00+09:00', '2023-02-01 00:00:00+09:00',
               '2023-03-01 00:00:00+09:00', '2023-04-01 00:00:00+09:00',
               '2023-05-01 00:00:00+09:00', '2023-06-01 00:00:00+09:00'],
              dtype='datetime64[ns, Asia/Seoul]', freq='MS')

In [138]:
ts_ms = pd.date_range(start='2023-01-01',  # 시작날자
                      end=None,            # 날자 범위 끝
                      periods=12,           # 생성할 TimeStamp 수
                      freq='M',            # 시간 간격(MS 월의 마지막)
                      tz = 'Asia/Seoul'    # 시간대
                     )
ts_ms

DatetimeIndex(['2023-01-31 00:00:00+09:00', '2023-02-28 00:00:00+09:00',
               '2023-03-31 00:00:00+09:00', '2023-04-30 00:00:00+09:00',
               '2023-05-31 00:00:00+09:00', '2023-06-30 00:00:00+09:00',
               '2023-07-31 00:00:00+09:00', '2023-08-31 00:00:00+09:00',
               '2023-09-30 00:00:00+09:00', '2023-10-31 00:00:00+09:00',
               '2023-11-30 00:00:00+09:00', '2023-12-31 00:00:00+09:00'],
              dtype='datetime64[ns, Asia/Seoul]', freq='M')

##### Period 배열

In [143]:
# 1개월길이로 Period 배열 만들기
pr_m = pd.period_range(start='2023-01-01',
                       end = None,
                       periods=3,
                       freq='M'
                      )
pr_m

PeriodIndex(['2023-01', '2023-02', '2023-03'], dtype='period[M]')

In [144]:
pr_m = pd.period_range(start='2023-01-01',
                       end = None,
                       periods=3,
                       freq='H'
                      )
pr_m

PeriodIndex(['2023-01-01 00:00', '2023-01-01 01:00', '2023-01-01 02:00'], dtype='period[H]')

In [145]:
pr_m = pd.period_range(start='2023-01-01',
                       end = None,
                       periods=3,
                       freq='2H'
                      )
pr_m

PeriodIndex(['2023-01-01 00:00', '2023-01-01 02:00', '2023-01-01 04:00'], dtype='period[2H]')

# 시계열 데이터 활용

In [146]:
df = pd.read_csv('https://raw.githubusercontent.com/leekyuyoung20221226/python/main/data/stock-data.csv')

In [148]:
# year month day 각각 컬럼을 만들어서 날자를 분리
# timestamp 형태로 변경한다음. period를 이용해서 년 월 일로 분리하고 각각 분리한 값을 컬럼을 생성해서 대입

In [154]:
df['new_date'] =  pd.to_datetime(df['Date'])
df['year'] =  df['new_date'].dt.year
df['month'] =  df['new_date'].dt.month
df['day'] =  df['new_date'].dt.day
df

Date  Close  Start   High    Low  Volume   new_date  year  month  \
0   2018-07-02  10100  10850  10900  10000  137977 2018-07-02  2018      7   
1   2018-06-29  10700  10550  10900   9990  170253 2018-06-29  2018      6   
2   2018-06-28  10400  10900  10950  10150  155769 2018-06-28  2018      6   
3   2018-06-27  10900  10800  11050  10500  133548 2018-06-27  2018      6   
4   2018-06-26  10800  10900  11000  10700   63039 2018-06-26  2018      6   
5   2018-06-25  11150  11400  11450  11000   55519 2018-06-25  2018      6   
6   2018-06-22  11300  11250  11450  10750  134805 2018-06-22  2018      6   
7   2018-06-21  11200  11350  11750  11200  133002 2018-06-21  2018      6   
8   2018-06-20  11550  11200  11600  10900  308596 2018-06-20  2018      6   
9   2018-06-19  11300  11850  11950  11300  180656 2018-06-19  2018      6   
10  2018-06-18  12000  13400  13400  12000  309787 2018-06-18  2018      6   
11  2018-06-15  13400  13600  13600  12900  201376 2018-06-15  2018      6   
12  2018-06-14  13450  13200  13700  13150  347451 2018-06-14  2018      6   
13  2018-06-12  13200  12200  13300  12050  558148 2018-06-12  2018      6   
14  2018-06-11  11950  12000  12250  11950   62293 2018-06-11  2018      6   
15  2018-06-08  11950  11950  12200  11800   59258 2018-06-08  2018      6   
16  2018-06-07  11950  12200  12300  11900   49088 2018-06-07  2018      6   
17  2018-06-05  12150  11800  12250  11800   42485 2018-06-05  2018      6   
18  2018-06-04  11900  11900  12200  11700   25171 2018-06-04  2018      6   
19  2018-06-01  11900  11800  12100  11750   32062 2018-06-01  2018      6   

    day  
0     2  
1    29  
2    28  
3    27  
4    26  
5    25  
6    22  
7    21  
8    20  
9    19  
10   18  
11   15  
12   14  
13   12  
14   11  
15    8  
16    7  
17    5  
18    4  
19    1