In [1]:
# 데이터 : fruits_300.npy   과일데이터  사과 파일애플 바나나
# 훈련용과 테스트용으로 데이터를 나눔
# 훈련용 1. 스케일, 2. 3dim -> 2dim
# dense
# Sequential
# compile
# fit
# evaluate

In [3]:
import numpy as np
import pandas as pd

In [4]:
fruits =  np.load('fruits_300.npy')
fruits.shape

(300, 100, 100)

In [6]:
target = [0]*100 + [1]*100 + [2]*100

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =  train_test_split(fruits, target, test_size=0.2, random_state=0)

In [8]:
x_train_scaled = x_train / 255.0
x_test_scaled = x_test / 255.0

In [9]:
x_train_scaled_reshape = x_train_scaled.reshape(-1,100*100)
x_test_scaled_reshape = x_test_scaled.reshape(-1,100*100)

In [12]:
x_train_scaled_reshape.shape, len(y_train)

((240, 10000), 240)

In [22]:
from tensorflow.keras.losses import sparse_categorical_crossentropy
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [23]:
dense = Dense(3,activation = 'softmax', input_shape=(10000,) )

In [24]:
model = Sequential(dense)

In [25]:
model.compile(loss=sparse_categorical_crossentropy, metrics='accuracy')

In [30]:
y_train = np.array(y_train)

In [31]:
model.fit(x_train_scaled_reshape,y_train, epochs=5)

Epoch 1/5
8/8 [==============================] - 0s 4ms/step - loss: 1.7015 - accuracy: 0.5958
Epoch 2/5
8/8 [==============================] - 0s 3ms/step - loss: 0.4359 - accuracy: 0.8625
Epoch 3/5
8/8 [==============================] - 0s 5ms/step - loss: 0.0790 - accuracy: 0.9917
Epoch 4/5
8/8 [==============================] - 0s 5ms/step - loss: 0.0553 - accuracy: 1.0000
Epoch 5/5
8/8 [==============================] - 0s 4ms/step - loss: 0.0404 - accuracy: 1.0000


In [32]:
y_test = np.array(y_test)

In [35]:
model.evaluate(x_test_scaled_reshape,y_test)

2/2 [==============================] - 0s 5ms/step - loss: 0.0382 - accuracy: 1.0000


[0.03816811367869377, 1.0]

In [43]:
y_test

array([2, 1, 0, 2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 2, 0, 0, 2, 0, 2, 1, 1, 1,
       1, 1, 2, 1, 1, 2, 2, 2, 0, 0, 0, 1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 1, 1, 0, 2, 1, 0, 2, 1])

In [37]:
predict_score = model.predict(x_test_scaled_reshape)

2/2 [==============================] - 0s 2ms/step


In [44]:
np.argmax(predict_score,axis=1)

array([2, 1, 0, 2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 2, 0, 0, 2, 0, 2, 1, 1, 1,
       1, 1, 2, 1, 1, 2, 2, 2, 0, 0, 0, 1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 1, 1, 0, 2, 1, 0, 2, 1], dtype=int64)

In [47]:
fruits_reshape = fruits.reshape(-1,100*100)
fruits_reshape_scaled = fruits_reshape / 255.0

In [49]:
total_score = model.predict(fruits_reshape_scaled)

10/10 [==============================] - 0s 2ms/step


In [50]:
np.argmax(total_score,axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], d

In [52]:
np.array(target)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])