# 분류 - classification
    고객분류, 질병진단, 스펨메일 필터링, 음성인식등... 카테고리를 갖는 경우
     - KNN, SVM, Decision Tree, Logistic Regression     

### KNN K-Nearst-Neighbors

# 1. 데이터 준비(확보)

In [319]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [320]:
titanic = sns.load_dataset('titanic')
titanic.rename(columns={'sex':'gender'},inplace=True)

In [321]:
titanic.head()

survived  pclass  gender   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

# 2.데이터 탐색 - info(), describe()

In [322]:
# 결측치 확인 - 1. 갯수, 2.형태는 숫자인데.. 타입이 object면 의심해 봐라.
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   gender       891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [323]:
# 결측치가 많은 컬럼은 통으로 제거하고. - deck 제거
# 의미가 비슷한 컬럼은 하나만 사용 -  embark_town 제거
titanic.drop(['deck','embark_town'],axis=1,inplace=True)

In [324]:
titanic.isna().sum()

survived        0
pclass          0
gender          0
age           177
sibsp           0
parch           0
fare            0
embarked        2
class           0
who             0
adult_male      0
alive           0
alone           0
dtype: int64

In [325]:
# embarked        2 --> 가장 많은 도시약자로 대체  fillna()

In [326]:
titanic['embarked'].value_counts()

S    644
C    168
Q     77
Name: embarked, dtype: int64

In [327]:
freq = titanic['embarked'].value_counts().idxmax()

In [328]:
titanic['embarked'].fillna(freq,inplace=True)

In [329]:
titanic.isnull().mean()

survived      0.000000
pclass        0.000000
gender        0.000000
age           0.198653
sibsp         0.000000
parch         0.000000
fare          0.000000
embarked      0.000000
class         0.000000
who           0.000000
adult_male    0.000000
alive         0.000000
alone         0.000000
dtype: float64

In [330]:
# age 처리여부. 
# 1 drop
# titanic = titanic.dropna(subset=['age'])

# 2.치환 - 선실등급(pclass)별 gender 별 평균으로 대체
grouped =  titanic.groupby(['pclass','gender'])

In [331]:
# transform  - 코드 채워넣기 - 20일차 소스 참고

In [332]:
# transform 이용하지 않고 파이썬 문법으로 원시 코드 구현

In [333]:
grouped_df = grouped['age'].mean()
# grouped_df[(1, 'female')]
grouped_df

pclass  gender
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: age, dtype: float64

In [334]:
# pclass == 1 gender == 'female'  34.611765
df = titanic[titanic.age.isnull()]

In [335]:
df.head()

survived  pclass  gender  age  sibsp  parch     fare embarked   class  \
5          0       3    male  NaN      0      0   8.4583        Q   Third   
17         1       2    male  NaN      0      0  13.0000        S  Second   
19         1       3  female  NaN      0      0   7.2250        C   Third   
26         0       3    male  NaN      0      0   7.2250        C   Third   
28         1       3  female  NaN      0      0   7.8792        Q   Third   

      who  adult_male alive  alone  
5     man        True    no   True  
17    man        True   yes   True  
19  woman       False   yes   True  
26    man        True    no   True  
28  woman       False   yes   True

In [336]:
idx1,idx2,idx3,idx4,idx5,idx6 = [],[],[],[],[],[]
for i in range(len(df)):
    if (df.iloc[i,1] == 1) & (df.iloc[i,2] == 'female') :        
        idx1.append(df.index[i])
    elif (df.iloc[i,1] == 1) & (df.iloc[i,2] == 'male') :
        idx2.append(df.index[i])
    elif (df.iloc[i,1] == 2) & (df.iloc[i,2] == 'female') :        
        idx3.append(df.index[i])
    elif (df.iloc[i,1] == 2) & (df.iloc[i,2] == 'male') :
        idx4.append(df.index[i])
    elif (df.iloc[i,1] == 3) & (df.iloc[i,2] == 'female') :        
        idx5.append(df.index[i])
    elif (df.iloc[i,1] == 3) & (df.iloc[i,2] == 'male') :
        idx6.append(df.index[i])    

In [337]:
# idx1 ~ idx5
titanic.iloc[idx1,3] = grouped_df.values[0]
titanic.iloc[idx2,3] = grouped_df.values[1]
titanic.iloc[idx3,3] = grouped_df.values[2]
titanic.iloc[idx4,3] = grouped_df.values[3]
titanic.iloc[idx5,3] = grouped_df.values[4]
titanic.iloc[idx6,3] = grouped_df.values[5]

In [338]:
titanic.isnull().sum()

survived      0
pclass        0
gender        0
age           0
sibsp         0
parch         0
fare          0
embarked      0
class         0
who           0
adult_male    0
alive         0
alone         0
dtype: int64

# 3. 속성선택

In [339]:
titanic.head(2)

survived  pclass  gender   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   

     who  adult_male alive  alone  
0    man        True    no  False  
1  woman       False   yes  False

In [340]:
df = titanic.loc[:,:'embarked']

In [341]:
df.drop(columns=['fare'],inplace=True)

In [342]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   gender    891 non-null    object 
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   embarked  891 non-null    object 
dtypes: float64(1), int64(4), object(2)
memory usage: 48.9+ KB


In [343]:
 # 범주형 데이터를 숫자로 변환 - one hot encoding

In [344]:
# 원핫인코딩
onehot_gender =  pd.get_dummies(df['gender'])
onehot_embarked = pd.get_dummies(df['embarked'],prefix='town')

In [345]:
df = pd.concat([df,onehot_gender,onehot_embarked],axis=1)

In [346]:
df.head()

survived  pclass  gender   age  sibsp  parch embarked  female  male  \
0         0       3    male  22.0      1      0        S       0     1   
1         1       1  female  38.0      1      0        C       1     0   
2         1       3  female  26.0      0      0        S       1     0   
3         1       1  female  35.0      1      0        S       1     0   
4         0       3    male  35.0      0      0        S       0     1   

   town_C  town_Q  town_S  
0       0       0       1  
1       1       0       0  
2       0       0       1  
3       0       0       1  
4       0       0       1

In [347]:
df.drop(columns=['gender','embarked'],inplace=True)

In [348]:
df.head()

survived  pclass   age  sibsp  parch  female  male  town_C  town_Q  town_S
0         0       3  22.0      1      0       0     1       0       0       1
1         1       1  38.0      1      0       1     0       1       0       0
2         1       3  26.0      0      0       1     0       0       0       1
3         1       1  35.0      1      0       1     0       0       0       1
4         0       3  35.0      0      0       0     1       0       0       1

# 훈련용/ 검증용 데이터 분할

In [349]:
y = df['survived']
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [350]:
x = df.loc[:,'pclass':]
x

pclass    age  sibsp  parch  female  male  town_C  town_Q  town_S
0         3  22.00      1      0       0     1       0       0       1
1         1  38.00      1      0       1     0       1       0       0
2         3  26.00      0      0       1     0       0       0       1
3         1  35.00      1      0       1     0       0       0       1
4         3  35.00      0      0       0     1       0       0       1
..      ...    ...    ...    ...     ...   ...     ...     ...     ...
886       2  27.00      0      0       0     1       0       0       1
887       1  19.00      0      0       1     0       0       0       1
888       3  21.75      1      2       1     0       0       0       1
889       1  26.00      0      0       0     1       1       0       0
890       3  32.00      0      0       0     1       0       1       0

[891 rows x 9 columns]

In [351]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x = ss.fit_transform(x)

In [352]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

# 모델선택 - 알고리즘

In [353]:
from sklearn.neighbors import KNeighborsClassifier

In [354]:
knn = KNeighborsClassifier(n_neighbors=5)

# 학습

In [355]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [356]:
y_hat = knn.predict(x_test)

In [357]:
y_hat[:10]

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1], dtype=int64)

In [358]:
y_test.values[:10]

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

# 평가

In [359]:
from sklearn import metrics

In [360]:
knn_matrix = metrics.confusion_matrix(y_test,y_hat)

In [361]:
knn_matrix

array([[134,  23],
       [ 34,  77]], dtype=int64)

In [362]:
#정확도 (Accuracy)  - 실제참과 예측참 + 실제거짓과 예측 거짓에대한 비율
#정밀도 (Precison)  - 모델을 기준으로 참으로 예측한 데이터들중에 실제 참인 비율 - 오류가 작다
#재현율(Recal) - 실제 참을 기준으로 모델이 얼마나 잘 맞추는지 재현하는것(시물레이션) - 오류가 낮다

In [363]:
knn_report = metrics.classification_report(y_test,y_hat)
print(knn_report)

              precision    recall  f1-score   support

           0       0.80      0.85      0.82       157
           1       0.77      0.69      0.73       111

    accuracy                           0.79       268
   macro avg       0.78      0.77      0.78       268
weighted avg       0.79      0.79      0.79       268



In [364]:
# 사망자에대한 예측능력 : 0.82
# 생존자에대한 예측능력 : 0.73

# svm : Support Vector Machine
    벡터개념을 가지고  공간을 분리 : 벡터개념은 2차원 평면 공간으로 만들어서 분리

In [365]:
from sklearn import svm

In [366]:
svm_model = svm.SVC()

In [367]:
svm_model.fit(x_train_scaled,y_train)

SVC()

In [368]:
y_hat = svm_model.predict(x_test_scaled)

In [369]:
print("첫 10개 실제 정답", y_test.values[:10])
print("첫 10개 예측     ", y_hat[:10])

첫 10개 실제 정답 [1 0 0 1 1 1 1 0 1 1]
첫 10개 예측      [0 0 0 1 1 1 1 0 1 1]


In [370]:
svm_report = metrics.classification_report(y_test,y_hat)
print(svm_report)

              precision    recall  f1-score   support

           0       0.79      0.94      0.86       157
           1       0.88      0.65      0.75       111

    accuracy                           0.82       268
   macro avg       0.83      0.79      0.80       268
weighted avg       0.83      0.82      0.81       268

