In [1]:
# file open -> file hander return
f = open('./test.txt', 'r')

In [2]:
contents = f.read()

In [4]:
contents

'HIGHLIGHTS: The Hilltoppers were defeated by Middleboro on the road. \nWinners for Durfee includes Michael Harrington in the 200 free (2:17.53) \nand Yasin Mahmoud in the 100 breaststroke (1:30.65). Harrington was part of the winning 200 \nfree relay with Cooper Long, Jack Fitzgerald, and William Rumsey (1:52.65). "All athletes stepped up at varying degrees, but special performances were had by Tim Archambault in the 200 IM and William Pierce," Hilltopper head coach Christopher Poliseno said.'

In [5]:
print(contents)

HIGHLIGHTS: The Hilltoppers were defeated by Middleboro on the road. 
Winners for Durfee includes Michael Harrington in the 200 free (2:17.53) 
and Yasin Mahmoud in the 100 breaststroke (1:30.65). Harrington was part of the winning 200 
free relay with Cooper Long, Jack Fitzgerald, and William Rumsey (1:52.65). "All athletes stepped up at varying degrees, but special performances were had by Tim Archambault in the 200 IM and William Pierce," Hilltopper head coach Christopher Poliseno said.


In [6]:
# 파일 사용이 끝나면 close() --> 자원 반납
f.close()

In [7]:
# 파일은 open ~ close 한쌍으로 동작
# 번거럽고 잊기 쉬워서 ... 개선
with open('test.txt', 'r') as f:
    content = f.read()
    print(content)

HIGHLIGHTS: The Hilltoppers were defeated by Middleboro on the road. 
Winners for Durfee includes Michael Harrington in the 200 free (2:17.53) 
and Yasin Mahmoud in the 100 breaststroke (1:30.65). Harrington was part of the winning 200 
free relay with Cooper Long, Jack Fitzgerald, and William Rumsey (1:52.65). "All athletes stepped up at varying degrees, but special performances were had by Tim Archambault in the 200 IM and William Pierce," Hilltopper head coach Christopher Poliseno said.


In [11]:
with open('test.txt', 'r') as f:
    content_list = f.readlines()  # 파일 전체 내용을 리스트로 반환
    print(content_list)

['HIGHLIGHTS: The Hilltoppers were defeated by Middleboro on the road. \n', 'Winners for Durfee includes Michael Harrington in the 200 free (2:17.53) \n', 'and Yasin Mahmoud in the 100 breaststroke (1:30.65). Harrington was part of the winning 200 \n', 'free relay with Cooper Long, Jack Fitzgerald, and William Rumsey (1:52.65). "All athletes stepped up at varying degrees, but special performances were had by Tim Archambault in the 200 IM and William Pierce," Hilltopper head coach Christopher Poliseno said.']


In [17]:
# 라인단위로 읽는 경우
with open('./test.txt', 'r') as f:
    # f.readline()으로 읽어서 값이 없을때 까지 f.readline()
    while True:
        content = f.readline()
        if not content: break
        content = content.replace('\n','')  # \n 이 출력되서 한줄씩 밀리는 현상 제거
        print(content)    

HIGHLIGHTS: The Hilltoppers were defeated by Middleboro on the road. 
Winners for Durfee includes Michael Harrington in the 200 free (2:17.53) 
and Yasin Mahmoud in the 100 breaststroke (1:30.65). Harrington was part of the winning 200 
free relay with Cooper Long, Jack Fitzgerald, and William Rumsey (1:52.65). "All athletes stepped up at varying degrees, but special performances were had by Tim Archambault in the 200 IM and William Pierce," Hilltopper head coach Christopher Poliseno said.


In [45]:
# 글자수(특수문자포함) count
# 공백을 기준으로 분리한 단어들의 count
# 라인수 count

with open('./test.txt', 'r') as f:
    content_list =  f.readlines()
    line_count = len(content_list)
    word_count = sum([len(line.split()) for line in content_list])        
    spel_count = sum([len(j) for j in [i.replace('\n','') for i in content_list]])
    print(f"라인수:{line_count}, 단어수 : {word_count}, 글자수 : {spel_count}")
    

라인수:4, 단어수 : 75, 글자수 : 491


In [47]:
with open('./hangule.txt', 'r', encoding='utf-8') as f:
    print(f.read())

서울=연합뉴스) 정아란 이동환 기자 = 대통령실은 군 당국의 북한 무인기 '부실 대응' 논란이 커지는 것과 관련, 군의 자체 감찰이 불가피하다는 기류다.

다만 일각에서 안보라인 수뇌부의 즉각 문책을 요구하는 데 대해선 신중한 태도를 보이는 모습이다.

대통령실 고위 관계자는 6일 연합뉴스와의 통화에서 "군이 북한 무인기 사태에 대한 내부 조사와 감찰을 진행할 것"이라면서 "어떻게 책임을 물어야 하는지는 군 내부적으로 판단하지 않겠느냐"고 말했다.

군 당국은 현재 자체 감찰이 진행되지 않고 있다고 밝혔지만, 감찰을 포함한 군 당국의 후속 조치가 있어야 한다는 게 대통령실의 전반적인 인식이다.


In [48]:
# word counter 
# 영문이든 한글이든. 텍스트 파일을 만들고 저장한다음 - non programming
# 각 단어가 몇번 출현(쓰였는지) 횟수
#    ex)  다만 : 2,  군 : 3

In [49]:
temp_list = ['the','abc', 'a','the', 'b','c']

In [52]:
word_count = {}
word_count['the']=1

In [54]:
word_count['the'] += 1

In [55]:
word_count

{'the': 2}

In [56]:
# 딕셔너리에서 키 값이 없으면 1로 만들어주고
# 다음에 또 같은 키가 들어오면 해당 키값을 += 1 로 증가한다

In [60]:
temp_list = ['the','abc', 'a','the', 'b','c']
word_count = {}
for word in temp_list:
    if word not in word_count.keys():
        word_count[word] = 1
    else:
        word_count[word] += 1
word_count        

{'the': 2, 'abc': 1, 'a': 1, 'b': 1, 'c': 1}

In [80]:
def makeWordCount(temp_list):
    word_count = {}
    for word in temp_list:
        if word not in word_count.keys():
            word_count[word] = 1
        else:
            word_count[word] += 1
    return word_count 

In [86]:
with open('./hangule.txt', 'r', encoding='utf-8') as f:
    temp = f.read().split()    
    result = makeWordCount(temp)    

In [88]:
# 2개이상 반복되서 나온 단어
[key for key,value in result.items() if value >=2]

['군', '당국의', '북한', '무인기', '자체', '감찰이', '감찰을']

# 넘파이
    외부모듈
    행렬, 선형대수, 통계

In [90]:
!pip install numpy

     --------------------------------------- 14.8/14.8 MB 31.2 MB/s eta 0:00:00


In [91]:
import numpy as np

    넘파이 배열 ndarray 

In [92]:
# 1차원 데이터 / 벡터(vector)
data_1 = [1, 2, 3, 4, 5]
data_1

[1, 2, 3, 4, 5]

In [93]:
# 2차원 데이터 / 행렬(Matrix)
data_2 = [
    [1,2,3],
    [4,5,6]
]
data_2

[[1, 2, 3], [4, 5, 6]]

In [94]:
data_3 = [
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
]    
data_3

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

    리스트 <--> 넘파이

In [97]:
vector_1 = np.array(data_1)
data_1, vector_1

([1, 2, 3, 4, 5], array([1, 2, 3, 4, 5]))

In [98]:
# 2차원 
matrix_1 = np.array(data_2)
# 3차원
matrix_2 = np.array(data_3)

In [99]:
matrix_1,  matrix_2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]))

In [100]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [101]:
np.zeros( (2,2) )

array([[0., 0.],
       [0., 0.]])

In [102]:
np.ones( (2,2) )

array([[1., 1.],
       [1., 1.]])

In [103]:
np.ones( (2,2,2) )

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [107]:
# 크기만 지정하고 데이터는 임의의 데이터로 채워짐
np.empty( (2,2))

array([[1., 1.],
       [1., 1.]])

In [109]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [110]:
np.full(5,3)

array([3, 3, 3, 3, 3])

In [111]:
np.full( (2,2), 10)

array([[10, 10],
       [10, 10]])

In [112]:
type(vector_1)

numpy.ndarray

In [113]:
# dtype : 자료형 안에 들어 있는 데이터의 타입
vector_1.dtype

dtype('int32')

In [115]:
# 자료형의 차수
vector_1.ndim

1

In [116]:
matrix_1.ndim,  matrix_2.ndim

(2, 3)

In [120]:
vector_1.shape

(5,)

In [118]:
# 행렬의 크기를 알려준다. 
# 1차원이면 갯수,
matrix_1.shape

(2, 3)

In [121]:
matrix_1

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
matrix_2.shape

(2, 2, 3)

In [123]:
matrix_2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [125]:
# 행렬의 개수
vector_1.size

5

In [126]:
matrix_1.size

6

In [127]:
matrix_2.size

12

    dtype
    다차원 배열을 생성할때 데이터 값을 지정할 수 있다

In [128]:
vec_dtype = np.array([1,2,3,4,5], dtype = np.int64)
matrix_dtype = np.array(
    [
        [1,2,3],
        [4,5,3]
    ],
    dtype = np.float64
)

In [ ]:
# 데이터 타입, 차수, 쉐이프