In [1]:
import numpy as np

In [2]:
matrix = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [3]:
matrix.shape

(3, 3)

In [5]:
print(f"합 : {np.sum(matrix)}")
print(f"합 : {matrix.sum()}")

print(f"평균 : {np.mean(matrix)}")
print(f"평균 : {matrix.mean()}")

print(f"표준편차 : {np.std(matrix)}")
print(f"표준편차 : {matrix.std()}")

print(f"분산 : {matrix.var()}")
print(f"분산 : {np.var(matrix)}")
#  min max는 각자 해 보기             

합 : 45
합 : 45
평균 : 5.0
평균 : 5.0
표준편차 : 2.581988897471611
표준편차 : 2.581988897471611
분산 : 6.666666666666667
분산 : 6.666666666666667


# 열과 행에서 최소 최소 및 기타 통계수치를 구해봅시다.
# min max를 예를 들어서 사용해보고 나머지는 각자 확인해 보세요

In [10]:
print(f"전체 데이터의 최대값 : {np.max(matrix)}")
print(f"열에서 최대값 : {np.max(matrix, axis = 0)}")
print(f"열에서 최소값 : {np.min(matrix, axis = 0)}")
print(f"열에서 평균값 : {np.mean(matrix, axis = 0)}")

전체 데이터의 최대값 : 9
열에서 최대값 : [7 8 9]
열에서 최소값 : [1 2 3]
열에서 평균값 : [4. 5. 6.]


In [11]:
print(f"행에서 최대값 : {np.max(matrix, axis = 1)}")
print(f"행에서 최소값 : {np.min(matrix, axis = 1)}")
print(f"행에서 평균값 : {np.mean(matrix, axis = 1)}")

행에서 최대값 : [3 6 9]
행에서 최소값 : [1 4 7]
행에서 평균값 : [2. 5. 8.]


# 난수생성

    seed : 씨앗( 콩심은데 콩나고 팥심은데 팥난다.)  1 ~ 100 사이의 임의수. 
    rand : 균등 분포한 난수를 생성
    random : 실수형 난수를 생성
    randint : 지정한 최소 최대범위안에서 난수 생성
    randn : 정규분포(평균:0, 표준편차:1)
    uniform : 임의의 분포에서 표본추출
    random_sample : 0.0 ~ 1.0 사이에서 실수
    standart_normal : 정규분포(평균:0, 표준편차:1)
    choice : 랜덤하게 샘플을 선택한다
    shuffle : 순서를 뒤섞는다.

In [13]:
# 난수를 생성(seed 값 고정)
np.random.seed(0)

In [18]:
import numpy.random as rd

In [22]:
print(f"0~0.1사이의 실수 난수 : {rd.random(10)}")
print(f"0~45사이의 6개 정수를 생성 : {rd.randint(0,46,6)}")
print(f"평균이 0.0 , 표준편차 1.0인 정규분포에서 5개 : {rd.normal(0.0,1.0,5)}")
print(f"{rd.standard_normal(3)}")

0~0.1사이의 실수 난수 : [0.45115921 0.01998767 0.44171092 0.97958673 0.35944446 0.48089353
 0.68866118 0.88047589 0.91823547 0.21682214]
0~45사이의 6개 정수를 생성 : [35 20 17 27 14 41]
평균이 0.0 , 표준편차 1.0인 정규분포에서 5개 : [ 0.42830357  0.99627783 -0.49114966  0.71267817  1.11334035]
[-2.15367459 -0.41611148 -1.07089699]


In [25]:
vector = [1,2,3,4,5,6,7,8,9]
rd.choice(vector,3)

array([9, 4, 9])

In [31]:
rd.shuffle(vector)

In [32]:
vector

[8, 3, 9, 4, 5, 1, 2, 6, 7]

# sort

In [34]:
# 평균이 0 이고 표준편차가 1인 정규분포 형태의 데이터 5
vector = np.random.randn(5)
vector

array([ 6.06389001e-01,  1.76084071e-03, -9.90160143e-01,  1.87239408e+00,
       -2.41073590e-01])

In [35]:
vector[0]

0.6063890007417859

In [36]:
vector

array([ 6.06389001e-01,  1.76084071e-03, -9.90160143e-01,  1.87239408e+00,
       -2.41073590e-01])

In [40]:
1e-01, 1e-02, 1e-03

(0.1, 0.01, 0.001)

In [41]:
1e+01, 1e+02, 1e+03

(10.0, 100.0, 1000.0)

In [43]:
# 정렬을 사용할때 옵션을 사용 안하면 기본이 ascending 오름차순
print(f"1차원 배열 sort() 정렬 전 : {vector}")
vector.sort()
print(f"1차원 배열 sort() 정렬 후 : {vector}")

1차원 배열 sort() 정렬 전 : [-9.90160143e-01 -2.41073590e-01  1.76084071e-03  6.06389001e-01
  1.87239408e+00]
1차원 배열 sort() 정렬 후 : [-9.90160143e-01 -2.41073590e-01  1.76084071e-03  6.06389001e-01
  1.87239408e+00]


In [60]:
# 2차원 데이터 정렬
matrix_1 = np.random.random((3,3))*10
matrix_1

array([[1.24833057, 7.22080662, 0.30452965],
       [7.4699424 , 0.92596165, 2.17450493],
       [7.49254417, 7.31693756, 0.45614637]])

In [64]:
print(f"2차원 배열 sort() 정렬 전 : \n{matrix_1}")
matrix_1.sort()
# matrix_1.sort(axis = 1)
print(f"\n2차원 배열 sort() 정렬 후 : \n{matrix_1}")

2차원 배열 sort() 정렬 전 : 
[[0.30452965 1.24833057 7.22080662]
 [0.92596165 2.17450493 7.4699424 ]
 [0.45614637 7.31693756 7.49254417]]

2차원 배열 sort() 정렬 후 : 
[[0.30452965 1.24833057 7.22080662]
 [0.92596165 2.17450493 7.4699424 ]
 [0.45614637 7.31693756 7.49254417]]


In [66]:
# 사용법을 알고싶으면 아래 주석을 제거하세요.
# help(matrix_1.sort)

In [68]:
import copy

In [69]:
matrix_1 = np.random.random((3,3))*10
matrix_2 =  copy.deepcopy( matrix_1)

In [70]:
matrix_1, matrix_2

(array([[1.816312  , 5.12393463, 5.80447137],
        [7.87542156, 6.0647546 , 2.18402855],
        [4.55168815, 8.78869742, 4.92268242]]),
 array([[1.816312  , 5.12393463, 5.80447137],
        [7.87542156, 6.0647546 , 2.18402855],
        [4.55168815, 8.78869742, 4.92268242]]))

In [71]:
matrix_1.sort()
matrix_1

array([[1.816312  , 5.12393463, 5.80447137],
       [2.18402855, 6.0647546 , 7.87542156],
       [4.55168815, 4.92268242, 8.78869742]])

In [72]:
matrix_2.sort(axis=1)
matrix_2

array([[1.816312  , 5.12393463, 5.80447137],
       [2.18402855, 6.0647546 , 7.87542156],
       [4.55168815, 4.92268242, 8.78869742]])

In [73]:
matrix_2.sort(axis=0)
matrix_2

array([[1.816312  , 4.92268242, 5.80447137],
       [2.18402855, 5.12393463, 7.87542156],
       [4.55168815, 6.0647546 , 8.78869742]])

In [74]:
matrix_1 = np.random.random((3,3))*10
matrix_1

array([[7.15561157, 4.8615956 , 7.0854815 ],
       [4.98140226, 8.44550079, 1.94342223],
       [7.7332601 , 9.74258664, 8.62309777]])

In [77]:
# 첫번째 행만 정렬
print(f"2차원 배열의 첫 번째 행만 정렬 전 \n:{matrix_1}")
matrix_1[0,:].sort() # default axis = 1
print(f"2차원 배열의 첫 번째 행만 정렬 후 \n:{matrix_1}")
      

2차원 배열의 첫 번째 행만 정렬 전 
:[[7.15561157 4.8615956  7.0854815 ]
 [4.98140226 8.44550079 1.94342223]
 [7.7332601  9.74258664 8.62309777]]
2차원 배열의 첫 번째 행만 정렬 후 
:[[4.8615956  7.0854815  7.15561157]
 [4.98140226 8.44550079 1.94342223]
 [7.7332601  9.74258664 8.62309777]]


In [76]:
# 슬라이스를 이용해서 첫번째 행만 가져오기
matrix_1[0,:]

array([7.15561157, 4.8615956 , 7.0854815 ])

In [81]:
# argsort : key를 기준으로 데이터를 정렬
matrix_1 = np.random.randn(5,5)
print("랜덤으로 생성된 2차원 배열 \n",matrix_1)

랜덤으로 생성된 2차원 배열 
 [[ 0.05334491 -1.5180287  -1.89304483 -0.78508653 -1.60529407]
 [ 1.43184023 -1.94219012  1.13995339 -0.61716593 -1.77555859]
 [-1.11820547 -1.60638701 -0.81467608  0.3212809  -0.12393044]
 [ 0.02212126 -0.32128651  0.69261805 -0.35352352  0.81228996]
 [-1.14178779 -0.28754879  1.31554171  0.68578051  0.52459879]]


In [82]:
# key 가 되는 1차원 배열을 생성
vector = np.array([5,3,1,2,4])

In [84]:
np.array([5,3,1,2,4]).argsort()
#         0 1 2 3 4
#         1 2 3 4 5

array([2, 3, 1, 4, 0], dtype=int64)

In [83]:
matrix_1[0] = vector
print(f"matrix 배열에 첫 번째 열에 vector 배열의 요소값 대입:\n{matrix_1}")

matrix 배열에 첫 번째 열에 vector 배열의 요소값 대입:
[[ 5.          3.          1.          2.          4.        ]
 [ 1.43184023 -1.94219012  1.13995339 -0.61716593 -1.77555859]
 [-1.11820547 -1.60638701 -0.81467608  0.3212809  -0.12393044]
 [ 0.02212126 -0.32128651  0.69261805 -0.35352352  0.81228996]
 [-1.14178779 -0.28754879  1.31554171  0.68578051  0.52459879]]


In [86]:
# 주어진 하나 이상의 숫자(key)를 기준으로 데이터를 정렬할때 argsort() 사용
print(f"argsort()로 정렬된 배열\n{matrix_1[ :, matrix_1[0].argsort() ] }")

argsort()로 정렬된 배열
[[ 1.          2.          3.          4.          5.        ]
 [ 1.13995339 -0.61716593 -1.94219012 -1.77555859  1.43184023]
 [-0.81467608  0.3212809  -1.60638701 -0.12393044 -1.11820547]
 [ 0.69261805 -0.35352352 -0.32128651  0.81228996  0.02212126]
 [ 1.31554171  0.68578051 -0.28754879  0.52459879 -1.14178779]]


In [88]:
matrix_1[ :, [2, 3, 1, 4, 0] ]

array([[ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ],
       [ 1.13995339, -0.61716593, -1.94219012, -1.77555859,  1.43184023],
       [-0.81467608,  0.3212809 , -1.60638701, -0.12393044, -1.11820547],
       [ 0.69261805, -0.35352352, -0.32128651,  0.81228996,  0.02212126],
       [ 1.31554171,  0.68578051, -0.28754879,  0.52459879, -1.14178779]])

In [93]:
matrix_1[ :, 2:3 ], matrix_1[ :, 3:4 ]

(array([[ 1.        ],
        [ 1.13995339],
        [-0.81467608],
        [ 0.69261805],
        [ 1.31554171]]),
 array([[ 2.        ],
        [-0.61716593],
        [ 0.3212809 ],
        [-0.35352352],
        [ 0.68578051]]))

In [96]:
# 행렬 즉 매트릭스를 만들고... from ~ to 형태로 데이터 가져오는거 연습
temp = np.random.randn(3,3)
temp

array([[ 0.3464808 , -0.45487435,  0.19809488],
       [ 0.39140807, -3.17786023, -0.95657514],
       [-0.03127493,  1.03272369, -1.21561912]])

In [100]:
temp[0,0], temp[0,1], temp[0,2], temp[0,-1]

(0.3464808006324303,
 -0.4548743493949417,
 0.1980948832062204,
 0.1980948832062204)

In [104]:
temp[0,(0,1,2) ],  temp[0, 0:3 ], temp[0, :3 ]

(array([ 0.3464808 , -0.45487435,  0.19809488]),
 array([ 0.3464808 , -0.45487435,  0.19809488]),
 array([ 0.3464808 , -0.45487435,  0.19809488]))

In [108]:
temp[(0,1,2), 0], temp[0:3, 0], temp[:3, 0], temp[: , 0]

(array([ 0.3464808 ,  0.39140807, -0.03127493]),
 array([ 0.3464808 ,  0.39140807, -0.03127493]),
 array([ 0.3464808 ,  0.39140807, -0.03127493]),
 array([ 0.3464808 ,  0.39140807, -0.03127493]))

# 배열의 크기 바꾸기

In [111]:
# 배열의 크기가  (5 , 4) 행렬 즉 matrix  데이터는 1 ~ 20
data = np.zeros((5,4))
count = 1
for i in range(5):
    for j in range(4):
        data[i,j] = count
        count += 1

In [112]:
data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])

In [113]:
# (4,5)  (2,10)

In [116]:
# data가 리스트형태이면 넘파이로 변환
# data = np.array(data)

data.reshape(5,4)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])

In [118]:
# 주의사항 배열의 크기를 변경할때는 행과 열의 수가 같아야 한다.
# 따라서 함수 또는 shape 를 사용해서 크기를먼저 알아야 함
print(f"matrix size : {data.size}")
print(f"matrix shape : {data.shape}")

matrix size : 20
matrix shape : (5, 4)


In [123]:
# reshape 할때 자주 사용하는기능... -1   맨 마지막 한개...
print(f"reshape(1,-1)\n {data.reshape(1,-1)}")
print(f"reshape(1,20)\n {data.reshape(1,20)}")
print(f"reshape(-1,20)\n {data.reshape(-1,20)}")

reshape(1,-1)
 [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20.]]
reshape(1,20)
 [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20.]]
reshape(-1,20)
 [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20.]]


In [129]:
# row 2
data.reshape(-1,10)

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]])

# 전치

In [132]:
type(data), data

(numpy.ndarray,
 array([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]]))

In [133]:
data.T

array([[ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.],
       [ 4.,  8., 12., 16., 20.]])

In [134]:
data.transpose()

array([[ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.],
       [ 4.,  8., 12., 16., 20.]])

In [137]:
data.swapaxes(0,1)

array([[ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.],
       [ 4.,  8., 12., 16., 20.]])

In [138]:
data  # 원본은 바뀌지 않는다.

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])

In [141]:
# [1,2,3,4,5,6,7,8,9,10,,,,,,]
data.reshape(1,-1)

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20.]])

In [145]:
data.reshape(1,-1)[0]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [144]:
data.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [148]:
# flatten() 함수는 데이터를 1차원 데이터로 손쉽게 만들어 준다.
np.zeros((10,2,3)).flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [149]:
# sample 함수
from random import sample

In [152]:
sample([1,2,3,4,5,6,7], 3)

[4, 3, 5]

In [153]:
np.random.choice([1,2,3,4,5,6,7],3)

array([3, 6, 2])

# 넘파이 산술 연산과 선형대수

In [157]:
# 넘파이 2차원 배열 2개.. 각각 (3,3)  (3,3)
m1 = np.array([
    [1,2,3],[4,5,6],[7,8,9]
])

# m2  0~20중에서 임의로
m2 = np.array(sample(range(20), 9))
m2 = m2.reshape(3,3)
# 각각의 메트릭스(행렬) 모양을 확인
m1.shape, m2.shape

((3, 3), (3, 3))

In [158]:
m1, m2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 2, 15, 11],
        [18, 19,  5],
        [16, 10,  6]]))

In [159]:
# list vs numpy

In [160]:
list_1 = [1,2,3,4,5]
list_1 + 2

TypeError: can only concatenate list (not "int") to list

In [161]:
m1,   m1+2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [162]:
# 나머지 4칙연산은 직접 해 보세요..

In [163]:
# 매트릭스 끼리 연산

In [165]:
m1, m2, m1 + m2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 2, 15, 11],
        [18, 19,  5],
        [16, 10,  6]]),
 array([[ 3, 17, 14],
        [22, 24, 11],
        [23, 18, 15]]))

In [166]:
# (3,3)  + [x,x,x]  : 행렬 + 벡터  (3,3) + (3,0)

In [174]:
m1, m1 + [1,0,1]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10]]))

In [175]:
# (3,3)  + (3,1)
m1,  m1 + [ [1],[0],[1]]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 2,  3,  4],
        [ 4,  5,  6],
        [ 8,  9, 10]]))

In [176]:
# (3,3)  + (2,3)
m1,  m1 + [ [1,1,1],[1,1,1]]

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [177]:
# (3,3)  + (3,2)
m1,  m1 + [ [1,1],[1,1],[1,1]]

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [179]:
# 행렬 내적.. dot
# shape의 모양이 중요하다... 공식...
# (3,3) dot (3, 1)    (3,1)

In [185]:
np.dot(m1,m2), np.matmul(m1,m2), m1@m2

(array([[ 86,  83,  39],
        [194, 215, 105],
        [302, 347, 171]]),
 array([[ 86,  83,  39],
        [194, 215, 105],
        [302, 347, 171]]),
 array([[ 86,  83,  39],
        [194, 215, 105],
        [302, 347, 171]]))

In [184]:
# 파이썬 버전 3.5 이상
m1@m2

array([[ 86,  83,  39],
       [194, 215, 105],
       [302, 347, 171]])